name: Docker Image Publish

on:
  push:
    branches: [ "Ec2_dev" ]

jobs:
  build:
    name: Build Image and Push to Dockerhub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: mlopspod2
          password: ${{ secrets.DOCKER }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mlopspod2/senti-analyzer:latest

  deploy:
    name: Deploy Image from Dockerhub to EC2 
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script:  |
            docker stop backend_server || true && docker rm backend_server || true
            docker pull mlopspod2/senti-analyzer
            docker run --detach --name backend_server -p 8501:8501 mlopspod2/senti-analyzer
            
